# Day 3: NumPy - Numerical Computing

NumPy is a Python library used for numerical computations.
It provides fast and efficient array operations compared to normal Python lists.

In this notebook, I will practice:
- Creating NumPy arrays
- Indexing and slicing arrays
- Boolean masking
- Vectorized operations
- Broadcasting

In [1]:
# import Numpy

import numpy as np
print(np.__version__)

2.5.1


## Creating NumPy Arrays

In this section, I create NumPy arrays using different methods.

NumPy arrays are faster than Python lists because they store data efficiently and allow vectorized operations.

In [ ]:
import numpy as np

# Create array from Python list
arr = np.array([1, 2, 3, 4, 5])
print(arr)

#Array of zeros
zeros_arr = np.zeros(5)
print(zeros_arr)

#Array of ones
ones_arr = np.ones(5)
print(ones_arr)

#Value from 0 to 10 with step 2
val_arr = np.arange(0, 10, 2) #arange(start, stop, step)
print(val_arr)

#Evenly spaced values
even_arr = np.linspace(0, 10, 5) #linspace(start, stop, num)
print(even_arr)

[1 2 3 4 5]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0 2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]


## Understanding Array Attributes

Every NumPy array has important properties:
- shape: shows the dimensions of the array.
- dtype: shows the data type.
- ndim: shows the number of dimensions.

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]]) # 2D array  

print("Shape:", arr.shape) #shape means the number of rows and columns in the array
print("Data type:", arr.dtype) #dtype means the data type of the elements in the array
print("Dimensions:", arr.ndim) #ndim means the number of dimensions of the array

Shape: (2, 3)
Data type: int64
Dimensions: 2


## Indexing and Slicing Arrays

NumPy allows accessing specific elements or parts of arrays.

For 2D arrays:
array[row, column]

In [12]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

# First row, third column
print(matrix[0,2]) #indexing take the element at the specified row and column:array[row, column]

# Second column
print(matrix[:,1]) #slicing take part of the array :array[start:stop]

# Second row
print(matrix[1,:]) #slicing take part of the array :array[start:stop]

#first row
print(matrix[0]) 
#last row
print(matrix[-1])

#last element
print(arr[-1,-1])

3
[2 5]
[4 5 6]
[1 2 3]
[4 5 6]
6


## Vectorized Operations

Vectorization allows performing operations on the whole array without using loops.

It is faster and more efficient because NumPy performs calculations using optimized C code.

In [21]:
a = np.array([1,2,3,4])

print(a * 2)
print(a + a)
print(a.mean())
print(a + 10)

b = np.array([[1,2,3],[4,5,6]])
print(b * 2)

#print(a+b) #this will give an error because the shapes of the arrays are not compatible for broadcasting

c = np.array([[1,2,3],[4,5,6]])
print(b+c)

print("_________________")

d = np.array([4,16,36,81])
print(np.sqrt(d))

[2 4 6 8]
[2 4 6 8]
2.5
[11 12 13 14]
[[ 2  4  6]
 [ 8 10 12]]
[[ 2  4  6]
 [ 8 10 12]]
_________________
[2. 4. 6. 9.]


In [22]:
#Example of vectorization (convert grades for all students to percentage)
grades = np.array([85, 90, 78, 92, 88])
percentages = grades / 100
print(percentages)

[0.85 0.9  0.78 0.92 0.88]


## Boolean Masking // array[condition]

Boolean masking is used to select elements that satisfy a condition.

It is useful for filtering data in machine learning datasets.

In [27]:
numbers = np.array([1,2,3,4,5,6])

filtered = numbers[numbers > 3] #conditional inside the array to show elements 
print(filtered)

filtered = numbers > 3 # without show the value of the elements, it will show True or False
print(filtered) 

#chose the elements that are even
even = numbers[numbers % 2 == 0]
print(even)

#more than one condition
filtered = numbers[(numbers > 2) & (numbers < 5)] #and condition
print(filtered)

#2D array
data = np.array([
    [10, 20],
    [30, 40],
    [50, 60]
])

print(data[data > 30])

[4 5 6]
[False False False  True  True  True]
[2 4 6]
[3 4]
[40 50 60]


## Broadcasting

Broadcasting allows NumPy to perform operations between arrays with compatible shapes.

It avoids manually repeating values and makes computations easier.

In [ ]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

row = np.array([10,20,30])
result = matrix + row

print(result)

# NumPy Array Manipulation Task

In this task, I practice the main NumPy concepts learned in this section.

The goal is to:
- Create a 2D array with values from 1 to 16.
- Check the array shape and data type.
- Use slicing to extract specific rows and columns.
- Apply boolean masking to filter values based on a condition.
- Use broadcasting to perform operations between arrays with different shapes.

These operations are important in data science and machine learning because NumPy arrays are used for efficient numerical computations and data processing.

In [28]:
import numpy as np

# Step 1: Create a 2D array of shape (4, 4) with values from 1 to 16
array = np.arange(1, 17).reshape(4, 4)

# Print the created array
print("Original Array:")
print(array)

# Print the shape and data type of the array
print("Shape:", array.shape)
print("Dtype:", array.dtype)


# Step 2: Use slicing to extract the second column and the last row

# Extract the second column from all rows
second_column = array[:, 1]

# Extract the last row from the array
last_row = array[-1, :]

# Print the extracted values
print("\nSecond Column:")
print(second_column)

print("Last Row:")
print(last_row)


# Step 3: Use boolean masking to select values greater than the array mean

# Calculate the mean value of the array
mean_value = array.mean()

# Select only values greater than the mean
greater_than_mean = array[array > mean_value]

# Print the mean and filtered values
print("\nMean Value:")
print(mean_value)

print("Values greater than mean:")
print(greater_than_mean)


# Step 4: Add a 1D row array to every row using broadcasting

# Create a 1D array that will be added to each row
row_array = np.array([10, 20, 30, 40])

# Add the row array to the 2D array using broadcasting
broadcast_result = array + row_array

# Print the row array and the final result
print("\nRow Array:")
print(row_array)

print("Result after Broadcasting:")
print(broadcast_result)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Shape: (4, 4)
Dtype: int64

Second Column:
[ 2  6 10 14]
Last Row:
[13 14 15 16]

Mean Value:
8.5
Values greater than mean:
[ 9 10 11 12 13 14 15 16]

Row Array:
[10 20 30 40]
Result after Broadcasting:
[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]
 [23 34 45 56]]
