# Why Linear Algebra?

Machine Learning models do not work directly with tables.

They convert datasets into vectors and matrices.

Every prediction made by a machine learning model is based on mathematical operations such as:

- Dot Product
- Matrix Multiplication

Linear Algebra is therefore considered the language of Machine Learning.

| Age | GPA | Hours Study |
| --- | --- | ----------- |
| 20  | 3.2 | 4           |
| 21  | 2.9 | 2           |
| 19  | 3.8 | 6           |

# Modle:(Matrix)
[
 [20,3.2,4],
 [21,2.9,2],
 [19,3.8,6]
]

# Vectors

A vector is an ordered list of numbers.

In Machine Learning, each data sample is represented as a vector.

Example:

[22, 3.6, 90]

This vector can represent:

- Age
- GPA
- Exam Score

In [2]:
import numpy as np

student = np.array([22, 3.6, 90])

print(student)
print(student.shape)

[22.   3.6 90. ]
(3,)


# Matrices

A matrix is a two-dimensional array.

Rows represent data samples.

Columns represent features.

Example:

[
 [22,3.6,90],
 [21,3.1,75],
 [23,3.9,98]
]

In [3]:
import numpy as np

students = np.array([
    [22,3.6,90],
    [21,3.1,75],
    [23,3.9,98]
])

print(students)
print(students.shape)
print(students[0])
print(students[:,1])

[[22.   3.6 90. ]
 [21.   3.1 75. ]
 [23.   3.9 98. ]]
(3, 3)
[22.   3.6 90. ]
[3.6 3.1 3.9]


# Dot Product

The dot product multiplies corresponding elements of two vectors and sums the results.

It is the core operation used by many machine learning models to make predictions.

Prediction = Dot Product(Features, Weights)

In [4]:
import numpy as np

features = np.array([25,50000,3])

weights = np.array([0.1,0.0002,1.5])

prediction = np.dot(features,weights)

print(prediction)

17.0


# Matrix Multiplication

Matrix multiplication allows machine learning models to compute predictions for multiple samples simultaneously.

The shapes must be compatible.

Example:

Matrix (Samples × Features)

×

Weight Vector (Features)

=

Prediction Vector (Samples)

In [5]:
X = np.array([
    [25,50000,3],
    [40,80000,10]
])
w = np.array([0.1,0.0002,1.5])

predictions = X @ w

print(predictions)

[17. 35.]


# Hands-On Lab

# Task 1: Creating a Matrix

## Objective
Represent three data samples as a NumPy matrix.

Each row represents one sample.

Each column represents one feature.

In [6]:
import numpy as np

X = np.array([
    [25, 50000, 3],
    [40, 80000, 10],
    [33, 62000, 5]
])

print(X)
print(X.shape)

[[   25 50000     3]
 [   40 80000    10]
 [   33 62000     5]]
(3, 3)


# Explanation
The matrix contains 3 rows, representing three data samples.
It contains 3 columns, representing the features (Age, Income, Experience).
The shape (3, 3) confirms the matrix has 3 samples and 3 features.

# Task 2: Compute the Dot Product

## Objective
Calculate the prediction for one sample using the dot product.

The feature vector is multiplied by the weight vector.

In [7]:
import numpy as np

features = np.array([25, 50000, 3])

weights = np.array([0.1, 0.0002, 1.5])

manual_prediction = (
    25 * 0.1 +
    50000 * 0.0002 +
    3 * 1.5
)

print("Manual Prediction:", manual_prediction)

prediction = np.dot(features, weights)

print("NumPy Prediction:", prediction)

Manual Prediction: 17.0
NumPy Prediction: 17.0


# Task 3: Matrix Multiplication

## Objective
Use matrix multiplication to generate predictions for all samples simultaneously.

In [8]:
import numpy as np

X = np.array([
    [25, 50000, 3],
    [40, 80000, 10],
    [33, 62000, 5]
])

weights = np.array([0.1, 0.0002, 1.5])

predictions = X @ weights

print("Predictions:")
print(predictions)

Predictions:
[17.  35.  23.2]


# Task 4: Shape Mismatch Error

## Objective
Create a shape mismatch error intentionally, then explain why it happened and how to fix it.

In [10]:
import numpy as np

X = np.array([
    [25, 50000, 3],
    [40, 80000, 10],
    [33, 62000, 5]
])

wrong_weights = np.array([0.1, 0.0002])

try:
    result = X @ wrong_weights
    print(result)
except ValueError as e:
    print("Error:")
    print(e)

Error:
matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)
